### ISSUE TITLE
Motion blur corruption weird on synthetic data?

### ISSUE THREAD

**Issue by cwchenwang** [EPFL-VILAB/3DCommonCorruptions#3]
Hi, your work is very great and I have successfully produced 3D corruptions such as fog3D on synthetic data. However, the results for motion blur is a little weird, and I am not sure whether it is correct, below is clean data (I have preprocessed it to RGB before corruption), depth and corrupted xy motion blur:
![r_0_clean](https://user-images.githubusercontent.com/23579918/196039902-aa941e58-f36c-4b8f-8e1d-d7084ab8711b.png)
![r_0_depth_0136](https://user-images.githubusercontent.com/23579918/196039904-d2f29b7d-088c-4b9a-9d65-35fb290a086b.png)
![r_0](https://user-images.githubusercontent.com/23579918/196039922-2e525cf3-44c6-4109-804d-48990b4b1dc0.png)

**Comment by ofkar** [comment]
Hi @cwchenwang , there may be a few things to consider here:

1) If you are using predicted depth from a neural network, make sure it looks visually reasonable. Otherwise the resulting corruption will not look realistic.
2) Assuming you are using ground truth depth, you may be getting a bad result since there is not much depth variation in your image (i.e. there are only two planes corresponding to foreground and background). Maybe you can try changing the distance between the two. Also try this for other images, or even [the sample data](https://github.com/EPFL-VILAB/3DCommonCorruptions/tree/main/sample_data) we provided to see if the issue persists. 
3) Another solution could be changing the range of random camera motion applied [here](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/main/create_3dcc/motion_video/create_motion.py#L199-L204) or the number of frames generated to perform motion blur ([here](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/main/create_3dcc/motion_video/create_motion.py#L213-L218) and [here](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/main/create_3dcc/motion_video/create_motion.py#L272-L296)).

**Comment by cwchenwang** [comment]
@ofkar Thanks for your reply. I think the problem is mainly due to the narrow depth range of my data. I tried to change the random camera motion to (-10, 10) and frames to 5, the results look a little better:

![r_1](https://user-images.githubusercontent.com/23579918/196132218-35789f5d-c205-4c62-8f08-33b68b1690d5.png)

But there is still black corner and there are some shadows, I don't know if this is normal or not

**Comment by ofkar** [comment]
Right. Another thing you can try is to increase the number of inpainting locations performed along the trajectory ([here](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/main/create_3dcc/motion_video/common.py#L176-L179)) and increase the number of frames collected to produce a smoother blur.
