### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'VisionTransformer' object has no attribute 'dist_token'

### ISSUE THREAD

**Issue by Hank5120** [EPFL-VILAB/3DCommonCorruptions#4]
Hi,
I follow the installation to build the environment,and download the pretrained models.
When I run the command "python demo.py --task normal --img_path ./sample_data/demo_in/ --output_path ./sample_data/demo_out/ ",
the error happened. 
Do you have the same problem?
![Screenshot from 2023-01-11 19-56-44](https://user-images.githubusercontent.com/116187090/211800499-2c47afa5-cf99-4ba6-accb-e73a470984cf.png)

**Comment by ofkar** [comment]
Hi @Hank5120, thanks for the pointer! This is caused by an incompatibility between the latest timm package and the DPT implementation. You can resolve it by `pip install timm=0.5.4`. I also updated the [requirements.txt](https://github.com/EPFL-VILAB/3DCommonCorruptions/blob/main/tools/requirements.txt) to reflect this change.
